### ISSUE TITLE
Auto discovering

### ISSUE THREAD

**Issue by karborator** [ilson-nobrega/zf-apigility-doctrine-skeleton#1]
Hi , 

I have problem with auto discovering : 

"No entities found
Autodiscovery could not find any existing entities, or those entities have already been exposed through Doctrine-connected services."

./vendor/doctrine/doctrine-module/bin/doctrine-module orm:convert-mapping --namespace="Application\Entity\" --force  --from-database annotation ./module/Application/src

 [1045] Access denied for user 'username'@'localhost'

doctrine.local.php 

```
<?php
return array(
    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => array(
                    'charset' => 'utf8',
                    'host' => 'localhost',
                    'port' => '3306',
                    'username' => 'username',
                    'password' => 'password',
                    'dbname' => 'dbname',
                )
            )
        ),
    ),
);
```

Ho to fix it ?

**Comment by ilson-nobrega** [comment]
You need configure the database connection correctly:

`'params' => array(
                    'charset' => 'utf8',
                    'host' => 'localhost',
                    'port' => '3306',
                    'username' => 'YOUR USERNAME',
                    'password' => 'YOUR PASSWORD',
                    'dbname' => 'DATABASE THAT YOU'LL USE',
                )
`

**Comment by karborator** [comment]
I'm using correct data (just dont showing her here )

**Comment by ilson-nobrega** [comment]
The error that appears is: [1045] Access denied for user 'username'@'localhost'?

**Comment by ilson-nobrega** [comment]
Let-me see one thing
